#!/bin/bash
# CREATED BY ROM ROBOTICS MYANMAR LTD,.
if [[ -e /usr/local/bin/roscdd ]]
then
	echo "roscd exists. I will delete and renew it."
	sudo rm /usr/local/bin/roscdd
else
	echo "roscd doesn't exist. I will create it."
fi
rm roscdd && touch roscdd
echo "#!/bin/bash" >> roscdd
echo "if [[ \$# -ne 1 ]]" >> roscdd
echo "then " >> roscdd
echo '	echo "Usage: roscd <ros2_package>" ' >> roscdd
echo 'else ' >> roscdd
echo '	source ~/.bashrc ' >> roscdd
echo '	pkg_dir=`ros2 pkg prefix $1` ' >> roscdd
echo '	if [ ${pkg_dir:1:3} = "opt" ] ' >> roscdd
echo '	then ' >> roscdd
echo '		cd $pkg_dir/share/$1 ' >> roscdd
echo '	elif [[ ${pkg_dir:1:4} == "home" ]] ' >> roscdd
echo '	then ' >> roscdd
echo '		cd $pkg_dir && cd ../../src/$1 ' >> roscdd
echo '	else ' >> roscdd
echo '		echo "Error!" ' >> roscdd
echo '		echo "pkg prefix is $pkg_dir" ' >> roscdd
echo '	fi ' >> roscdd
echo 'fi ' >> roscdd
chmod +x roscdd

echo "" >> ~/.bashrc
echo "# ================= roscd for ROS2" >> ~/.bashrc
echo "alias roscd='. roscdd'" >> ~/.bashrc
sudo mv ./roscdd /usr/local/bin/roscdd
source ~/.bashrc
echo "Done! You can use roscd command with ROS2"

