#!/bin/bash

if [[ $# -ne 1 ]]
then
	echo "Usage: roscd <ros2_package>"
else
	echo "pkg check.."
	source ~/.bashrc
	pkg_dir=`ros2 pkg prefix $1`

	if [ ${pkg_dir:1:3} = "opt" ]
	then
		echo "In /opt/ dir"
		cd $pkg_dir/share/$1
	elif [[ ${pkg_dir:1:4} == "home" ]]
	then
		echo "In /home dir"
		cd $pkg_dir && cd ../../src/$1
	else
		echo "Error!"
		echo "pkg prefix is $pkg_dir"
	fi
	#cd $pkg_dir
	echo "changed!"
fi


