#!/bin/bash
#PATH_ = 'p'
source ~/.bashrc

case "$1" in
start)
	echo "roslaunch pkg launch"
	roslaunch $2 $3.launch
;;
stop)
	echo "rosnode killing"
	#for i in(rosnode list);
	#do
	#	rosnode kill $i
	#	echo " killing $i"
	#done
	killall roscore
	echo ""
	echo " Killing all roscore."

;;
enable)
	echo "Service Enabled"
	update-rc.d $1$2service defaults 99
;;
disable)
	echo "Service Disable"
	rm -f /etc/rc*/*$1$2*
;;
esac

