#!/bin/bash

echo ""
echo "          ROM ROBOTICS LTD     "
echo ""

# UPDATE, UPGRADE
echo ""
echo " ROM ROBOTICS LTD:: updating ......................................................."
echo ""
sudo apt update 
sudo apt upgrade -y

# INSTALL ROS2 FOXY
echo ""
echo " ROM ROBOTICS LTD:: installing ros2 foxy ..............."
echo ""
sudo apt update && sudo apt install locales
sudo locale-gen en_US en_US.UTF-8
sudo update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
export LANG=en_US.UTF-8
sudo apt update && sudo apt install curl gnupg2 lsb-release
sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key  -o /usr/share/keyrings/ros-archive-keyring.gpg
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null

sudo apt update
sudo apt install ros-foxy-desktop
echo "source /opt/ros/foxy/setup.bash" >> ~/.bashrc
sudo apt install python3-argcomplete
echo "export ROS_DOMAIN_ID=0" >> ~/.bashrc

printenv | grep -i ROS






