#!/bin/bash
echo ""
echo "OPEN SOURCE ROBOTICS FOR MYANMAR"
echo ""

for rosparam in $(rosparam list)
do
	rosparam delete $rosparam
	echo "[Deleting PARAMETER] $rosparam"
done

for rosnode in $(rosnode list)
do
	rosnode kill $rosnode
	echo "[Deleting Node] $rosnode"
done
rosnode kill /rosout
rosnode cleanup

