#!/bin/bash

# INSTALL BASIC FEATURES
sudo apt install -y vim git curl
mkdir -p ~/.vim/plugged
cp .vimrc ~/
cp .vimrc.plug ~/
curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# INSTALL NEO
echo " Clonning https://github.com/itchyny/lightline.vim"
git clone https://github.com/itchyny/lightline.vim ~/.vim/pack/plugins/start/lightline
git clone https://github.com/itchyny/lightline.vim ~/.vim/bundle/lightline.vim


echo " Open vim and type :PlugInstall in command mode"
echo " Check this url => "
echo " https://github.com/junegunn/vim-plug"

# sublime style
mkdir ~/vim/colors
cp sublimemonokai.vim ~/vim/colors/



