#!/bin/sh
PATH="/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"
source ~/.bashrc

case "$1" in
start)
	echo "roslaunch $2 $3"
	roslaunch $2 $3.launch
;;
stop)
	echo "rosnode killing"
	for i in(rosnode list);
	do
		rosnode kill $i
		echo " killing $i"
	done
	killall roscore
	echo " "
	echo " Killing all roscore."

;;
enable)
	echo "Service Enabled"
	update-rc.d $2$3service defaults 99
;;
disable)
	echo "Service Disable"
	rm -f /etc/rc*/*$2$3*
;;
esac

